(function(){
'use strict';
var ID='bmi-language-widget',PANEL_ID='bmi-language-panel',STYLE_ID='bmi-language-widget-style';
var LANDING='https://www.magyariskola.at/magyar-nyelv-oktatás-bécs';
var SELECTOR='https://programvalaszto.magyariskola.at/foglalkozasok.html';
var PROGRAMS=[
 {place:'Bécs 1. kerület · Schwedenplatz',name:'Magyar nyelv · 1. csoport',age:'6–10 év',when:'Szombat 10:00–12:00',url:'https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-1'},
 {place:'Bécs 1. kerület · Schwedenplatz',name:'Magyar nyelv · 2. csoport',age:'10–14 év',when:'Kéthetente szombat 12:00–14:00',url:'https://www.magyariskola.at/event-details/magyarnyelv-schwedenplatz-2'},
 {place:'Bécs · Aspern',name:'Magyar nyelv · Aspern',age:'6–10 év',when:'Kedd 15:30–17:00',url:'https://www.magyariskola.at/event-details/magyaroktatas-kedd-2026'},
 {place:'Bécs · Seestadt',name:'Magyar nyelv · Seestadt',age:'6–10 év',when:'Szerda 16:00–17:30',url:'https://www.magyariskola.at/event-details/magyarnyelv-szerda-2026'},
 {place:'Baden',name:'Magyar Iskola Badenben',age:'7–8 év · 1–2. osztály',when:'Kedd 16:00–17:30',url:'https://www.magyariskola.at/event-details/iskolabaden-2026'}
];
var favicon='https://programvalaszto.magyariskola.at/bmi-butterfly-favicon.png?v=20260902';var fav=document.querySelector('link[rel="icon"]');if(!fav){fav=document.createElement('link');fav.rel='icon';document.head.appendChild(fav)}fav.type='image/png';fav.href=favicon;document.querySelectorAll('link[rel="shortcut icon"]').forEach(function(x){x.remove()});
var style=document.getElementById(STYLE_ID);if(!style){style=document.createElement('style');style.id=STYLE_ID;style.textContent=''
+'#'+ID+'{position:fixed!important;right:max(18px,env(safe-area-inset-right))!important;bottom:max(18px,env(safe-area-inset-bottom))!important;z-index:2147483000!important;display:flex!important;align-items:center!important;gap:10px!important;height:58px!important;padding:0 17px 0 12px!important;border:1px solid rgba(0,0,0,.10)!important;border-radius:999px!important;background:rgba(255,255,255,.95)!important;backdrop-filter:saturate(180%) blur(18px)!important;-webkit-backdrop-filter:saturate(180%) blur(18px)!important;color:#111!important;box-shadow:0 10px 30px rgba(0,0,0,.14)!important;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif!important;font-size:14px!important;font-weight:680!important;letter-spacing:-.01em!important;cursor:pointer!important;transition:transform .18s ease,box-shadow .18s ease!important}'
+'#'+ID+':hover,#'+ID+':focus-visible{transform:translateY(-2px)!important;box-shadow:0 14px 36px rgba(0,0,0,.19)!important;outline:none!important}'
+'#'+ID+' .bmi-lang-icon{display:grid!important;place-items:center!important;width:36px!important;height:36px!important;flex:0 0 36px!important;border-radius:50%!important;background:linear-gradient(135deg,#ef476f,#ffd166 43%,#06d6a0 72%,#118ab2)!important;color:#fff!important;font-size:18px!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45)!important}'
+'#'+ID+' .bmi-lang-label{display:block!important;text-align:left!important;white-space:nowrap!important}#'+ID+' .bmi-lang-label small{display:block!important;margin-top:3px!important;color:#6e6e73!important;font-size:11px!important;font-weight:520!important}'
+'#'+PANEL_ID+'{position:fixed!important;right:max(18px,env(safe-area-inset-right))!important;bottom:88px!important;z-index:2147482999!important;width:min(440px,calc(100vw - 28px))!important;max-height:min(650px,calc(100vh - 125px))!important;overflow:auto!important;padding:18px!important;border:1px solid rgba(0,0,0,.09)!important;border-radius:24px!important;background:rgba(255,255,255,.98)!important;backdrop-filter:saturate(180%) blur(24px)!important;-webkit-backdrop-filter:saturate(180%) blur(24px)!important;box-shadow:0 24px 70px rgba(0,0,0,.20)!important;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif!important;color:#111!important;opacity:0!important;visibility:hidden!important;transform:translateY(10px) scale(.985)!important;transform-origin:bottom right!important;transition:opacity .16s ease,transform .16s ease,visibility .16s ease!important}'
+'#'+PANEL_ID+'.open{opacity:1!important;visibility:visible!important;transform:translateY(0) scale(1)!important}'
+'#'+PANEL_ID+' .bmi-lang-head{display:flex!important;align-items:flex-start!important;justify-content:space-between!important;gap:14px!important;margin-bottom:12px!important}#'+PANEL_ID+' h2{margin:0!important;font-size:21px!important;line-height:1.12!important;letter-spacing:-.035em!important}#'+PANEL_ID+' .bmi-lang-intro{margin:6px 0 0!important;color:#6e6e73!important;font-size:13px!important;line-height:1.42!important}'
+'#'+PANEL_ID+' .bmi-lang-close{appearance:none!important;border:0!important;background:#f2f2f7!important;color:#333!important;width:32px!important;height:32px!important;border-radius:50%!important;font-size:20px!important;line-height:1!important;cursor:pointer!important;flex:0 0 32px!important}'
+'#'+PANEL_ID+' .bmi-place{margin-top:13px!important}#'+PANEL_ID+' .bmi-place-title{margin:0 0 7px!important;font-size:11.5px!important;font-weight:780!important;letter-spacing:.045em!important;text-transform:uppercase!important;color:#59595f!important}'
+'#'+PANEL_ID+' .bmi-lang-program{display:grid!important;grid-template-columns:1fr auto!important;gap:5px 12px!important;padding:11px 12px!important;margin:0 0 7px!important;border:1px solid rgba(0,0,0,.075)!important;border-radius:15px!important;background:#fff!important;color:#111!important;text-decoration:none!important;transition:background .14s ease,transform .14s ease,border-color .14s ease!important}#'+PANEL_ID+' .bmi-lang-program:hover,#'+PANEL_ID+' .bmi-lang-program:focus-visible{background:#f7f7f8!important;border-color:rgba(0,0,0,.14)!important;transform:translateY(-1px)!important;outline:none!important}'
+'#'+PANEL_ID+' .bmi-lang-program b{font-size:13.5px!important;line-height:1.28!important;font-weight:690!important}#'+PANEL_ID+' .bmi-lang-program .age{font-size:12px!important;font-weight:740!important;color:#0066cc!important;white-space:nowrap!important}#'+PANEL_ID+' .bmi-lang-program .meta{grid-column:1/-1!important;color:#6e6e73!important;font-size:11.5px!important;line-height:1.35!important}'
+'#'+PANEL_ID+' .bmi-lang-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;margin-top:13px!important}#'+PANEL_ID+' .bmi-lang-action{display:flex!important;align-items:center!important;justify-content:center!important;min-height:42px!important;padding:0 10px!important;border-radius:13px!important;background:#111!important;color:#fff!important;text-decoration:none!important;text-align:center!important;font-size:12.5px!important;font-weight:680!important}#'+PANEL_ID+' .bmi-lang-action.secondary{background:#f2f2f7!important;color:#111!important}'
+'@media(max-width:720px){#'+ID+'{right:max(12px,env(safe-area-inset-right))!important;bottom:max(12px,env(safe-area-inset-bottom))!important;width:62px!important;height:62px!important;padding:0!important;justify-content:center!important;border-radius:50%!important}#'+ID+' .bmi-lang-icon{width:42px!important;height:42px!important;flex-basis:42px!important;font-size:20px!important}#'+ID+' .bmi-lang-label{position:absolute!important;width:1px!important;height:1px!important;margin:-1px!important;overflow:hidden!important;clip-path:inset(50%)!important;white-space:nowrap!important}#'+PANEL_ID+'{left:12px!important;right:12px!important;bottom:86px!important;width:auto!important;max-height:calc(100vh - 110px)!important;border-radius:22px!important;padding:16px!important;transform-origin:bottom center!important}#'+PANEL_ID+' .bmi-lang-actions{grid-template-columns:1fr!important}}';document.head.appendChild(style)}
var old=document.querySelector('.whatsapp-community');if(old)old.remove();var oldWidget=document.getElementById('bmi-whatsapp-widget');if(oldWidget)oldWidget.remove();
var btn=document.getElementById(ID);if(!btn){btn=document.createElement('button');btn.id=ID;btn.type='button';document.body.appendChild(btn)}btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-controls',PANEL_ID);btn.setAttribute('aria-label','Magyar nyelvű oktatás gyorsmenü megnyitása');btn.innerHTML='<span class="bmi-lang-icon" aria-hidden="true">A</span><span class="bmi-lang-label">Magyar nyelvű oktatás<small>5 csoport · Bécs és Baden</small></span>';
var panel=document.getElementById(PANEL_ID);if(!panel){panel=document.createElement('section');panel.id=PANEL_ID;panel.setAttribute('aria-label','Magyar nyelvű oktatás');document.body.appendChild(panel)}
function esc(s){return String(s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
var places=[];PROGRAMS.forEach(function(p){if(places.indexOf(p.place)===-1)places.push(p.place)});var html='<div class="bmi-lang-head"><div><h2>Magyar nyelvű oktatás</h2><p class="bmi-lang-intro">Öt kiemelt iskolás csoport Bécsben és Badenben. Írás, olvasás, szövegértés, szókincs és beszédfejlesztés korosztályhoz igazítva.</p></div><button class="bmi-lang-close" type="button" aria-label="Bezárás">×</button></div>';
places.forEach(function(place){html+='<div class="bmi-place"><div class="bmi-place-title">'+esc(place)+'</div>';PROGRAMS.filter(function(p){return p.place===place}).forEach(function(p){html+='<a class="bmi-lang-program" href="'+esc(p.url)+'" target="_blank" rel="noopener"><b>'+esc(p.name)+'</b><span class="age">'+esc(p.age)+'</span><span class="meta">'+esc(p.when)+'</span></a>'});html+='</div>'});html+='<div class="bmi-lang-actions"><a class="bmi-lang-action" href="'+LANDING+'" target="_blank" rel="noopener">Magyar nyelvi képzések</a><a class="bmi-lang-action secondary" href="'+SELECTOR+'" target="_blank" rel="noopener">Programválasztó</a></div>';panel.innerHTML=html;
function closePanel(){panel.classList.remove('open');btn.setAttribute('aria-expanded','false')}function openPanel(){panel.classList.add('open');btn.setAttribute('aria-expanded','true');var first=panel.querySelector('a,button');if(first)first.focus()}btn.addEventListener('click',function(){panel.classList.contains('open')?closePanel():openPanel()});panel.querySelector('.bmi-lang-close').addEventListener('click',function(){closePanel();btn.focus()});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&panel.classList.contains('open')){closePanel();btn.focus()}});document.addEventListener('click',function(e){if(panel.classList.contains('open')&&!panel.contains(e.target)&&!btn.contains(e.target))closePanel()});
})();
